[project]
name = "back-end"
version = "0.1.0"
description = "Simple back-end server test using fastapi and faker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.12.0",
    "fastapi[standard]>=0.121.0",
]
